# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.0.1"

gem "iban_bic", path: "../.."
gem "sqlite3"
gem "rspec-core"

group :development, :test do
  gem "byebug", platform: :mri
end
